# Generated by Django 3.1.7 on 2021-03-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CostosCirugia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modelo',
        ),
    ]
