# Generated by Django 3.1.7 on 2021-03-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CostosCirugia', '0002_delete_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_act', models.CharField(max_length=20, null=True, unique=True, verbose_name='Nombre de la Actividad')),
            ],
            options={
                'ordering': ['nombre_act'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=30, null=True, unique=True, verbose_name='Cargo')),
                ('descripcion', models.CharField(max_length=30, null=True, verbose_name='Descripción de Cargo')),
                ('valor', models.FloatField(verbose_name='Valor Costo Salario Mensual')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoCanasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_canasta', models.CharField(max_length=85, null=True, unique=True, verbose_name='Concepto de la Canasta')),
            ],
            options={
                'ordering': ['nombre_canasta'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoHonorarioSalario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concep_hon', models.CharField(max_length=30, null=True, unique=True, verbose_name='Nombre del Concepto')),
            ],
            options={
                'ordering': ['nombre_concep_hon'],
            },
        ),
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss_adicional', models.FloatField(null=True, verbose_name='Porcentaje Ganancia')),
                ('valor_uvt', models.FloatField(default=0, null=True, verbose_name='Valor UVT Especialistas')),
                ('smdlv', models.FloatField(default=0, null=True, verbose_name='Salaraio Minimo Diario L.V.')),
            ],
            options={
                'ordering': ['iss_adicional'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True, unique=True, verbose_name='Nombre del Insumo')),
                ('codigo', models.CharField(max_length=30, null=True, verbose_name='Codigo del Insumo')),
                ('presentacion', models.CharField(max_length=30, null=True, verbose_name='Presentación')),
                ('valor', models.FloatField(verbose_name='Valor Compra')),
            ],
        ),
        migrations.CreateModel(
            name='NombreCanasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_canasta', models.CharField(max_length=85, null=True, unique=True, verbose_name='Nombre de la Canasta')),
            ],
            options={
                'ordering': ['nombre_canasta'],
            },
        ),
        migrations.CreateModel(
            name='TipoEstancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_est', models.CharField(max_length=60, null=True, verbose_name='Tipo de Estancia')),
                ('numero_camas', models.IntegerField(default=0, null=True, verbose_name='Número de Camas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_proc', models.CharField(max_length=80, null=True, unique=True, verbose_name='Nombre de la Especialidad')),
            ],
            options={
                'ordering': ['nombre_tipo_proc'],
            },
        ),
    ]
