# Generated by Django 3.1.7 on 2021-03-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CostosCirugia', '0003_actividad_cargo_conceptocanasta_conceptohonorariosalario_constante_insumo_nombrecanasta_tipoestancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cup', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Cups')),
                ('cod_soat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código SOAT')),
                ('nombre_proc', models.CharField(max_length=190, null=True, unique=True, verbose_name='Nombre del Procedimiento')),
                ('duracion_proc', models.FloatField(null=True, verbose_name='Duración en minutos')),
                ('uvr', models.FloatField(blank=True, default=0, null=True, verbose_name='UVR')),
                ('conts_soat', models.FloatField(blank=True, default=0, null=True, verbose_name='Constante SOAT')),
                ('dias_estancia', models.IntegerField(default=0, null=True, verbose_name='Días Estancia')),
                ('NombreCanasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.nombrecanasta', verbose_name='Canasta')),
                ('tipoProcedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.tipoprocedimiento', verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='HonorarioSalario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALARIO', 'SALARIO'), ('HONORARIO', 'HONORARIO')], default='SALARIO', max_length=9, verbose_name='TIPO DE PAGO')),
                ('costo', models.FloatField(blank=True, default=0, null=True, verbose_name='Costo no Paramertrizado')),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.actividad', verbose_name='Ubicación')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.cargo', verbose_name='Cargo')),
                ('conceptoHonorarioSalario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.conceptohonorariosalario', verbose_name='Concepto')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.procedimiento', verbose_name='Procedimiento')),
                ('tipoProcedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.tipoprocedimiento', verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_estancia', models.CharField(max_length=40, null=True, verbose_name='Concepto Estancia')),
                ('valor_concepto', models.FloatField(default=0, null=True, verbose_name='Valor día')),
                ('dividir_por_cama', models.BooleanField(default=True, verbose_name='¿Se divide entre el número de camas ?')),
                ('tipoEstancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CostosCirugia.tipoestancia', verbose_name='Tipo de Estancia')),
            ],
        ),
        migrations.CreateModel(
            name='Canasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1, null=True, verbose_name='Cantidad')),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.actividad', verbose_name='Ubicación')),
                ('conceptoCanasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.conceptocanasta', verbose_name='Concepto')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.insumo', verbose_name='Insumo')),
                ('nombreCanasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.nombrecanasta', unique=True, verbose_name='Nombre de la Canasta')),
            ],
        ),
    ]
