# Generated by Django 3.1.7 on 2021-03-12 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CostosCirugia', '0004_canasta_estancia_honorariosalario_procedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canasta',
            name='nombreCanasta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.nombrecanasta', verbose_name='Nombre de la Canasta'),
        ),
    ]
