# Generated by Django 3.1.7 on 2021-03-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CostosCirugia', '0006_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimiento',
            old_name='NombreCanasta',
            new_name='nombreCanasta',
        ),
    ]
