# Generated by Django 3.1.7 on 2021-03-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CostosCirugia', '0011_auto_20210315_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='conceptoInsumo',
            field=models.CharField(choices=[('DESECHABLE', 'DESECHABLE'), ('MEDICAMENTO', 'MEDICAMENTO'), ('DISPOSITIVOS MEDICOS', 'DISPOSITIVOS MEDICOS'), ('PAQUETE DESECHABLE', 'PAQUETE DESECHABLE'), ('LIMPIEZA', 'LIMPIEZA'), ('PAQUETE REUTILIZABLE', 'PAQUETE REUTILIZABLE')], default='MEDICAMENTO', max_length=20, verbose_name='Concepto Insumo'),
        ),
    ]
