# Generated by Django 3.1.7 on 2021-03-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CostosCirugia', '0012_auto_20210315_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constante',
            options={},
        ),
        migrations.RemoveField(
            model_name='honorariosalario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cargo',
            name='tipo',
            field=models.CharField(choices=[('SALARIO', 'SALARIO'), ('HONORARIO', 'HONORARIO'), ('CONSULTAS', 'CONSULTAS')], default='SALARIO', max_length=9, verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='tipoProcedimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostosCirugia.tipoprocedimiento', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='constante',
            name='derecho_sala',
            field=models.FloatField(null=True, verbose_name='Derecho de Sala'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='valor',
            field=models.FloatField(verbose_name='Costo'),
        ),
    ]
