# Generated by Django 3.1.7 on 2021-03-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CostosCirugia', '0013_auto_20210316_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='valor',
            field=models.FloatField(verbose_name='Costo por hora'),
        ),
    ]
