# Generated by Django 3.1.7 on 2021-03-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CostosCirugia', '0014_auto_20210316_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='tipo',
            field=models.CharField(choices=[('SALARIO', 'SALARIO'), ('CONSULTAS', 'CONSULTAS'), ('HONORARIO ANESTESIOLOGIA', 'HONORARIO ANESTESIOLOGIA'), ('HONORARIO ESPECIALISTA', 'HONORARIO ESPECIALISTA')], default='SALARIO', max_length=24, verbose_name='Concepto'),
        ),
    ]
