# Generated by Django 3.1.7 on 2021-03-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CostosCirugia', '0015_auto_20210316_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='constante',
            name='estancia',
            field=models.FloatField(null=True, verbose_name='Estancia'),
        ),
    ]
