# Generated by Django 3.1.7 on 2021-03-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CostosCirugia', '0016_constante_estancia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estancia',
        ),
    ]
